<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5798" started-at="2015-05-05T17:59:16Z" finished-at="2015-05-05T17:59:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5798" started-at="2015-05-05T17:59:16Z" finished-at="2015-05-05T17:59:22Z">
      <class name="com.example.tests.GroupRemovalTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.GroupRemovalTests@2d6d8735]" name="setUp" is-config="true" duration-ms="2749" started-at="2015-05-05T21:59:16Z" finished-at="2015-05-05T21:59:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deleteSomeGroup()[pri:0, instance:com.example.tests.GroupRemovalTests@2d6d8735]" name="deleteSomeGroup" duration-ms="2893" started-at="2015-05-05T21:59:19Z" finished-at="2015-05-05T21:59:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [23] but found [21]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [23] but found [21]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.example.tests.GroupRemovalTests.deleteSomeGroup(GroupRemovalTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteSomeGroup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.GroupRemovalTests@2d6d8735]" name="tearDown" is-config="true" duration-ms="156" started-at="2015-05-05T21:59:22Z" finished-at="2015-05-05T21:59:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.GroupRemovalTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
