<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CutehomePC" name="com.example.tests.ContactCreationTests" tests="5" failures="5" timestamp="16 Jun 2015 19:38:45 GMT" time="0.001" errors="0">
  <testcase name="testContactCreation" time="0.000" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:18)
	at com.example.fw.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at com.example.fw.HibernateHelper.listGroups(HibernateHelper.java:19)
	at com.example.fw.ApplicationManager.<init>(ApplicationManager.java:23)
	at com.example.tests.TestBase.setUp(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.hibernate.InvalidMappingException: Unable to read XML
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:375)
	at org.hibernate.internal.util.xml.MappingReader.readMappingDocument(MappingReader.java:304)
	at org.hibernate.cfg.Configuration.add(Configuration.java:518)
	at org.hibernate.cfg.Configuration.add(Configuration.java:514)
	at org.hibernate.cfg.Configuration.add(Configuration.java:688)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:771)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2257)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2229)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2209)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2162)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2077)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:13)
	... 26 more
Caused by: org.dom4j.DocumentException: Error on line 6 of document  : Element type "property" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "property" must be followed by either attribute specifications, ">" or "/>".
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:325)
	... 38 more
]]>
    </failure>
  </testcase> <!-- testContactCreation -->
  <testcase name="testContactCreation" time="0.000" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:18)
	at com.example.fw.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at com.example.fw.HibernateHelper.listGroups(HibernateHelper.java:19)
	at com.example.fw.ApplicationManager.<init>(ApplicationManager.java:23)
	at com.example.tests.TestBase.setUp(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.hibernate.InvalidMappingException: Unable to read XML
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:375)
	at org.hibernate.internal.util.xml.MappingReader.readMappingDocument(MappingReader.java:304)
	at org.hibernate.cfg.Configuration.add(Configuration.java:518)
	at org.hibernate.cfg.Configuration.add(Configuration.java:514)
	at org.hibernate.cfg.Configuration.add(Configuration.java:688)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:771)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2257)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2229)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2209)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2162)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2077)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:13)
	... 26 more
Caused by: org.dom4j.DocumentException: Error on line 6 of document  : Element type "property" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "property" must be followed by either attribute specifications, ">" or "/>".
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:325)
	... 38 more
]]>
    </failure>
  </testcase> <!-- testContactCreation -->
  <testcase name="testContactCreation" time="0.000" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:18)
	at com.example.fw.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at com.example.fw.HibernateHelper.listGroups(HibernateHelper.java:19)
	at com.example.fw.ApplicationManager.<init>(ApplicationManager.java:23)
	at com.example.tests.TestBase.setUp(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.hibernate.InvalidMappingException: Unable to read XML
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:375)
	at org.hibernate.internal.util.xml.MappingReader.readMappingDocument(MappingReader.java:304)
	at org.hibernate.cfg.Configuration.add(Configuration.java:518)
	at org.hibernate.cfg.Configuration.add(Configuration.java:514)
	at org.hibernate.cfg.Configuration.add(Configuration.java:688)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:771)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2257)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2229)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2209)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2162)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2077)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:13)
	... 26 more
Caused by: org.dom4j.DocumentException: Error on line 6 of document  : Element type "property" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "property" must be followed by either attribute specifications, ">" or "/>".
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:325)
	... 38 more
]]>
    </failure>
  </testcase> <!-- testContactCreation -->
  <testcase name="testContactCreation" time="0.001" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:18)
	at com.example.fw.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at com.example.fw.HibernateHelper.listGroups(HibernateHelper.java:19)
	at com.example.fw.ApplicationManager.<init>(ApplicationManager.java:23)
	at com.example.tests.TestBase.setUp(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.hibernate.InvalidMappingException: Unable to read XML
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:375)
	at org.hibernate.internal.util.xml.MappingReader.readMappingDocument(MappingReader.java:304)
	at org.hibernate.cfg.Configuration.add(Configuration.java:518)
	at org.hibernate.cfg.Configuration.add(Configuration.java:514)
	at org.hibernate.cfg.Configuration.add(Configuration.java:688)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:771)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2257)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2229)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2209)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2162)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2077)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:13)
	... 26 more
Caused by: org.dom4j.DocumentException: Error on line 6 of document  : Element type "property" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "property" must be followed by either attribute specifications, ">" or "/>".
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:325)
	... 38 more
]]>
    </failure>
  </testcase> <!-- testContactCreation -->
  <testcase name="testContactCreation" time="0.000" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:18)
	at com.example.fw.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at com.example.fw.HibernateHelper.listGroups(HibernateHelper.java:19)
	at com.example.fw.ApplicationManager.<init>(ApplicationManager.java:23)
	at com.example.tests.TestBase.setUp(TestBase.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.hibernate.InvalidMappingException: Unable to read XML
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:375)
	at org.hibernate.internal.util.xml.MappingReader.readMappingDocument(MappingReader.java:304)
	at org.hibernate.cfg.Configuration.add(Configuration.java:518)
	at org.hibernate.cfg.Configuration.add(Configuration.java:514)
	at org.hibernate.cfg.Configuration.add(Configuration.java:688)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:771)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:2257)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:2229)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2209)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:2162)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2077)
	at org.hibernate.cfg.Configuration.configure(Configuration.java:2056)
	at com.example.fw.HibernateUtil.buildSessionFactory(HibernateUtil.java:13)
	... 26 more
Caused by: org.dom4j.DocumentException: Error on line 6 of document  : Element type "property" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "property" must be followed by either attribute specifications, ">" or "/>".
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.hibernate.internal.util.xml.MappingReader.legacyReadMappingDocument(MappingReader.java:325)
	... 38 more
]]>
    </failure>
  </testcase> <!-- testContactCreation -->
</testsuite> <!-- com.example.tests.ContactCreationTests -->
